title: micro:bit game controller with Scratch
hero_image: images/banner.png
description: Learn how to use a micro:bit to control a sprite in Scratch
original_url: https://raspberrypi.org/learning/microbit-game-controller
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-1, programming-1, phys-comp-2, manufacture-0, community-0
interests: ''
technologies: scratch
site_areas: ''
steps:
- title: Introduction
- title: What you will need
- title: Setting up the micro:bit
- title: Setting up the Python file
- title: Coding the micro:bit
- title: Setting up Scratch
- title: Making the assets
- title: Coding the rocket
- title: Coding the UFO
- title: Coding the missile
- title: What next?
